### ISSUE TITLE
Context being lost between @RabbitListener and Webclient

### ISSUE THREAD

**Issue by Jojoooo1** [spring-projects/spring-amqp#2560] opened 2023-11-23 15:46 UTC
**In what version(s) of Spring AMQP are you seeing this issue?**
3.1.0

**Describe the bug**
Trace are not being propagated between @RabbitListener and downstream webClient using Spring Boot 3.2 and reactor 3.6.0
```
[service-webhook] [pool-6-thread-4] [0846b5f279f31bdeaf059557fc0950a6-3f2563a3260e8510] c.s.webhook.clients.WebhookHttpClient    : HTTP[webhook] retryCount[0] url[https://webhook.site/b4b43dbd-9980-4690-8db7-e50be66e4d0c] body[{}]
[service-webhook] [or-http-epoll-4] [  this should have traces  ] c.s.webhook.clients.WebhookHttpClient    : HTTP[webhook] response '{}'
```
**To Reproduce**

clone project https://github.com/Jojoooo1/spring-microservice-webhook-reactive 

```bash
make start-rabbitmq
```
- Start application with `dev` profile
- Access RabbitMQ dashboard with user:password
- Access webhook queue http://localhost:15672/#/queues/%2F/webhook
- Publish message with header url: any-webhooksite-url body: {}

The code part is within the `WebhookHttpClient.java`
```java
   [...]
    return this.webClient
        .post()
        .uri(url)
        .contentType(MediaType.APPLICATION_JSON)
        .headers(
            httpHeaders ->
                headers.forEach((k, v) -> httpHeaders.add(k, v != null ? v.toString() : null)))
        .bodyValue(requestBody)
        .exchangeToMono(this::defaultResponseHandler)
   [...]
  private Mono<Void> defaultResponseHandler(final ClientResponse response) {
    final HttpStatusCode status = response.statusCode();

    return response
        // Does not enforce any class to keep http client generic.
        .bodyToMono(String.class)
        // Necessary to force mono execution on empty response.
        .defaultIfEmpty(StringUtils.EMPTY)
        .map(
            body -> {
              if (status.is2xxSuccessful()) {
                log.info("HTTP[webhook] response '{}'", body);
```
It is pretty strange as the context is only separate by an exchangeToMono and bodyToMono.

Initially opened issue within reactor repo https://github.com/reactor/reactor-core/issues/3648.

**Comment by garyrussell** [comment] 2023-11-23 16:02
See my comment on the referenced issue: https://github.com/reactor/reactor-core/issues/3648#issuecomment-1824661650

**Comment by garyrussell** [comment] 2023-11-23 16:05
Note that you need to enable observation in the listener container; it is disabled by default - see https://docs.spring.io/spring-amqp/docs/current/reference/html/#micrometer-observation

**Comment by Jojoooo1** [comment] 2023-11-23 16:08
Thanks for the response @garyrussell, indeed the two factories in the project are setting the observation.

**Comment by garyrussell** [comment] 2023-11-23 16:10
Thanks for the update; I didn't look at the project (it's a holiday here until Monday).

**Comment by Jojoooo1** [comment] 2023-11-23 16:13
Wow, sorry! Have a great time and forget about me! :D

**Comment by garyrussell** [comment] 2023-11-23 16:18
Bear in mind that the `Observation` created by the listener container only lives for the scope of the listener method; the observation is closed when the listener method returns. The container cannot handle async listener methods (it knows nothing about the actual listener method - that is all handled in the listener adapter).

I suspect you will need to handle it yourself in your listener.

**Comment by Jojoooo1** [comment] 2023-11-23 20:28
Very nice @chemicL !
Updating code with:
```java
    return this.webClient
        .post()
        .uri(url)
        .contentType(MediaType.APPLICATION_JSON)
        .headers(
            httpHeaders ->
                headers.forEach((k, v) -> httpHeaders.add(k, v != null ? v.toString() : null)))
        .bodyValue(requestBody)
        // Context is lost downstream
        .exchangeToMono(this::defaultResponseHandler)
        .tap(Micrometer.observation(this.registry))
```
worked like a charm

**Comment by chemicL** [comment] 2023-11-24 09:24
One more thought. As the listener method is invoked while an `Observation` is in scope, you might find it useful to call `.contextCapture()` after `.tap(Micrometer.observation(this.registry))`.
The listener adapter (`AbstractAdaptableMessageListener`) also subscribes while the `Observation` is still in scope, therefore this way you'd be able to establish a parent-child relationship between the `Observation` that is immediately finished after the `Mono` is returned. However, you'd be able to correlate any logs that you perform before you actually return the `Mono`. It would also mean that messages in the same batch share the trace-id of the batch.

@garyrussell please consider including these remarks in the documentation for reactive types. I'm happy to help as well.

**Comment by sinfull1** [comment] 2023-12-11 06:21
unfortunately, this is not working for me.. for the headers copy step

.headers(
            httpHeaders ->
                headers.forEach((k, v) -> httpHeaders.add(k, v != null ? v.toString() : null)))

What is the source of this headers.forEach, for reactor Kafka I see only traceheader  propagated.

Is there a way to instrument this in the back ground, my use case is a Kafka consumer on receiving a message from source, executes a web client call. This call needs to be in the same trace..

**Comment by artembilan** [comment] 2023-12-11 19:38
@sinfull1 ,

I don't think the Reactor Kafka is related somehow to this issue.

@chemicL ,

I'm not sure what we need to document since that `contextCapture()` is a standard Reactor functionality if we would like to propagate the current thread context to the reactive stream we initiate from there: https://projectreactor.io/docs/core/release/reference/#_contextcapture_operator.

Closing this as `Works as Designed`.

Will be happy to reopen if there is really a reasonable justification what we have to document.

**Closed by artembilan** 2023-12-11 19:38 UTC
Labels: status: waiting-for-reporter

**Comment by chemicL** [comment] 2023-12-13 12:53
> I'm not sure what we need to document since that `contextCapture()` is a standard Reactor functionality if we would like to propagate the current thread context to the reactive stream we initiate from there: https://projectreactor.io/docs/core/release/reference/#_contextcapture_operator.

The contextCapture() operator doesn't help in this context unfortunately, as was explained in my earlier comments.

> Will be happy to reopen if there is really a reasonable justification what we have to document.

I can just point back to what I previously said:
https://github.com/spring-projects/spring-amqp/issues/2560#issuecomment-1824867877

Just to reiterate, after having worked with @olegz on the spring-cloud-stream case which looks very much like this one here, we came up with what can be seen in their documentation. I believe it was justified there the same way it is for this project.

**Comment by chemicL** [comment] 2023-12-14 13:25
> I'm not sure what we need to document since that `contextCapture()` is a standard Reactor functionality if we would like to propagate the current thread context to the reactive stream we initiate from there: https://projectreactor.io/docs/core/release/reference/#_contextcapture_operator.

The `contextCapture()` operator on its own doesn't help much in this context, as was explained in my earlier comments (observation is immediately stopped). The situation is quite tricky for users in my opinion.

> Will be happy to reopen if there is really a reasonable justification what we have to document.

I can just point back to what I previously said: https://github.com/spring-projects/spring-amqp/issues/2560#issuecomment-1824867877

Just to reiterate, after having worked with @olegz on the spring-cloud-stream case which looks very much like this one here, we came up with what can be seen in their documentation. I believe it was justified there the same way it is for this project and either I am failing to find this [in the existing documentation](https://docs.spring.io/spring-amqp/docs/current/reference/html/#micrometer-observation) or there is potential to do [the same brief explanation as in spring-cloud-stream's case](https://docs.spring.io/spring-cloud-stream/reference/observability.html#_reactive_functions).

I believe this issue could be renamed to something like "Document observability for listeners with asynchronous types" and reopened.

**Comment by artembilan** [comment] 2023-12-14 14:50
We probably need to write some unit test to verify such a behavior, but at a glance it must work.
We do this:
```
observation.observe(() -> executeListenerAndHandleException(channel, data));
```
So, an `Observation` is set into `ThreadLocal`.
Then within that `executeListenerAndHandleException()` we do this:
```
((Mono<? super Object>) returnValue).subscribe(success, failure, completeConsumer);
```
And if that `returnValue` has a `contextCapture()` it must get an effect taking the current observation from the  `ThreadLocal`.
So, that all should work OK even if we close an observation immediately after returning from the listener method call.
I see the code in question is like this:
```
    .map(
            body -> {
              if (status.is2xxSuccessful()) {
                log.info("HTTP[webhook] response '{}'", body);
```
In my experience only `handle()` operator does a log correlation 🤷

**Comment by chemicL** [comment] 2023-12-15 10:14
> In my experience only `handle()` operator does a log correlation 🤷

@Jojoooo1 [uses the new Spring Boot 3.2](https://github.com/Jojoooo1/spring-microservice-webhook-reactive/blob/develop/src/main/resources/application.yaml#L54) config for [automatic propagation to other operators](https://projectreactor.io/docs/core/release/reference/#_automatic_mode).

I'll try to play with it a bit and perhaps prepare a more limited example as a unit test to validate the case.
