### ISSUE TITLE
ShutdownSignalException when sending message to RabbitMQ after app restart/launch for the first time

### ISSUE THREAD

**Issue by purbarunc** [spring-projects/spring-amqp#2729] opened 2024-06-10 14:47 UTC
I am getting the `ShutdownSignalException ` exception when attempting to send message to the RabbitMQ. The weird thing is this happens the very first time when the spring boot app is launched or restarted. This automatically gets fixed in the second and subsequent attempts and hence I don't believe there shouldn't be any configuration issue. Hence, I am not able to debug the issue

> Below given is the error log.

com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'MyTopicExchange' in vhost '/': received 'topic' but current is 'direct', class-id=40, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:528) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:349) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:193) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:125) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:761) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.AMQConnection.access$400(AMQConnection.java:48) ~[amqp-client-5.21.0.jar:5.21.0]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:688) ~[amqp-client-5.21.0.jar:5.21.0]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

![image](https://github.com/spring-projects/spring-amqp/assets/28572738/6cf72812-05fe-4f98-9520-4da2799f836f)

> My RabbitMQ Exchange and Queue configuration in the Management console is as below:

![image](https://github.com/spring-projects/spring-amqp/assets/28572738/9d14dee0-842e-4aca-a8a5-5af8c300816f)
![image](https://github.com/spring-projects/spring-amqp/assets/28572738/1ea157f6-dbf0-496b-93da-5a1d7a491297)

> Code is given in the below link:

https://github.com/purbarunc/Spring-Boot-RabbitMQ/tree/master/RabbitMQPub

Please have a look into the same.

**Comment by artembilan** [comment] 2024-06-10 17:29
Sorry, not clear how to reproduce.
Would you mind including some instructions or test?
I wrote this test:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureWebTestClient
class RabbitMqPubApplicationTests {

	@Autowired
	WebTestClient webTestClient;

	@Test
	void contextLoads() {
				webTestClient.post().uri("/order")
						.contentType(MediaType.APPLICATION_JSON)
						.bodyValue(new OrderRequest("test", 2, 100))
						.exchange()
						.expectStatus()
						.is2xxSuccessful();
	}

}
```
for your `RabbitMQPub` project, and it passes well without any errors in logs.
(Right, I also changed to `implementation 'org.springframework.boot:spring-boot-starter-webflux'` dependency to make value of `WebTestClient`).

**Comment by artembilan** [comment] 2024-06-10 18:28
Well, technically that `received 'topic' but current is 'direct'` error means that you have already a `MyTopicExchange` of type `direct` before you start your application.
Therefore when `RabbitAdmin` tries to configure those entities from your application, it encounters that mismatch and raises error.
So, if you remove that exchange from your broker before you start the application, everything should be OK.
Or change its type to `topic` on the broker side.

I'll keep this opened for a couple days before closing since it looks like `Works as Designed`.

**Comment by purbarunc** [comment] 2024-06-11 05:04
@artembilan Perfect! Changing the exchange type to **topic** instead of **direct** in the RabbitMQ Management console fixed the issue. 
![image](https://github.com/spring-projects/spring-amqp/assets/28572738/1f9612be-304a-4471-8c98-d855ca4e4370)

But I wonder when the exchange type was direct it was working fine from second attempt onwards. (exception was thrown only for the first time after the app gets launch/reload) which is strange.

But anyway, appreciate the help. Thanks !

**Comment by artembilan** [comment] 2024-06-11 14:45
Yeah... Sorry: forgot to explain what is going on.

The `RabbitAdmin` in the application tries to created broker objects when connection is established. Essentially for the first time you produce a message from your application.
On the second time the connection is already there, therefore no attempts to recreate those objects.
And it works before you just produce to some exchange with some routing key. 
And apparently it matches to the binding even if it is not a topic exchange.
Indeed the first publication fails because objects cannot be (re)created on the broker withing the same call stack.

Closed as `Works as Designed`

**Closed by artembilan** 2024-06-11 14:45 UTC
Labels: status: waiting-for-reporter, type: bug
