### ISSUE TITLE
AmqpRejectAndDontRequeueException completely restarts Consumer

### ISSUE THREAD

**Issue by alexey-anufriev** [spring-projects/spring-amqp#2591] opened 2023-12-21 11:52 UTC
## Prerequisites

- Spring AMQP v3.1.0
- AMQP Listener in Manual Ack mode that needs 2 seconds (just `Thread.sleep`) to process the message;
- PostProcessor that drop the second (!) message right away;

### Test Flow

- Message 1 is being sent;
- Message 1 is being consumed by the listener;
- Message 1 starts processing (it needs to 2 seconds to complete it, before it is Ack-ed);
- Message 2 is being sent;
- PostProcessor throws `AmqpRejectAndDontRequeueException` to drop Message 2;

### Expected Result

- Message 2 is dropped;
- Message 1 is processed and Ack-ed.

### Actual Result

- After `AmqpRejectAndDontRequeueException`, Consumer is restarted;
- Delivery tags of the messages are cleared, so no way to ack/nack messages properly;
- Message 1 cannot be Ack-ed anymore due to error: `unknown delivery tag 1`.

**Sample**

https://github.com/alexey-anufriev/spring-amqp-bulk-reject

Clone and run: `mvn clean test`

**Comment by artembilan** [comment] 2023-12-21 20:34
Thank you for the sample!

Looking to your code, I see the trap:
```
new Thread(() -> {
```
So, you deliberately hand off processing to a different thread.
This way an `AsyncMessageProcessingConsumer` is able to move on in its `mainLoop()` for the `Message message = consumer.nextMessage(this.receiveTimeout);`.
Therefore it is not a surprise that second message is rejected before the first has reached its `channel.basicAck(tag, false);`.

There is a logic:
```
long tagToRollback = isAsyncReplies()
							? message.getMessageProperties().getDeliveryTag()
							: -1;
```
which is used for `consumer.rollbackOnExceptionIfNecessary(ex, tagToRollback);`.
And that one does this:
```
		boolean ackRequired = !this.acknowledgeMode.isAutoAck()
				&& (!this.acknowledgeMode.isManual() || ContainerUtils.isRejectManual(ex));
...
if (ackRequired) {
				if (tag < 0) {
					OptionalLong deliveryTag = this.deliveryTags.stream().mapToLong(l -> l).max();
					if (deliveryTag.isPresent()) {
						this.channel.basicNack(deliveryTag.getAsLong(), true,
								ContainerUtils.shouldRequeue(this.defaultRequeueRejected, ex, logger));
					}
```
Pay attention to the `true` argument for `basicNack`:
```
    /**
     * Reject one or several received messages.
     *
     * Supply the <code>deliveryTag</code> from the {@link com.rabbitmq.client.AMQP.Basic.GetOk}
     * or {@link com.rabbitmq.client.AMQP.Basic.Deliver} method containing the message to be rejected.
     * @see com.rabbitmq.client.AMQP.Basic.Nack
     * @param deliveryTag the tag from the received {@link com.rabbitmq.client.AMQP.Basic.GetOk} or {@link com.rabbitmq.client.AMQP.Basic.Deliver}
     * @param multiple true to reject all messages up to and including
     * the supplied delivery tag; false to reject just the supplied
     * delivery tag.
     * @param requeue true if the rejected message(s) should be requeued rather
     * than discarded/dead-lettered
     * @throws java.io.IOException if an error is encountered
     */
    void basicNack(long deliveryTag, boolean multiple, boolean requeue)
```
Therefore the first message is also nack'ed since it is a part of tags we are rejecting.

Doesn't look like this has anything to do with restarting.
And even it happens, that is just a consequence of the previously mentioned multi-nack: we end up not having respective tag to manually ack when your thread in the listener is resumed.

Consider to adjust your `demoListener()`  method to return `Mono<Void>` or `CompletableFuture<Void>` to let the listener to treat it as an async mode.
That way only one second message is going to nack'ed.
When I changed your listener to this:
```
   @RabbitListener(queues = "demo-queue", containerFactory = "demoRabbitConnectionFactory")
    public CompletableFuture<Void> demoListener(String payload, @Header(AmqpHeaders.DELIVERY_TAG) final long tag) {
        return CompletableFuture.runAsync(() -> {
            log.info("Received message with tag: {}", tag);

            try {
                log.info("Started processing message with tag: {}", tag);
                Thread.sleep(2000L); // simulate some off-line processing
                log.info("Finished processing message with tag: {}", tag);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            log.info("Accepted message {} with tag: {}", payload, tag);
        });
    }
```

Your test must be adjusted as well since there is no `Channel.close()` anymore therefore your `DemoShutdownListener`  is not called.

See more info in docs: https://docs.spring.io/spring-amqp/reference/amqp/receiving-messages/async-returns.html

Closing this as `Works as Designed`.

**Closed by artembilan** 2023-12-21 20:34 UTC
Labels: type: bug, status: waiting-for-triage

**Comment by alexey-anufriev** [comment] 2023-12-22 15:23
Thank you for the detailed explanation @artembilan!
