### ISSUE TITLE
Upgrade from 2.1.2 to 2.1.3 results in "Property 'connectionFactory' is required"

### ISSUE THREAD

**Issue by sanderino666** [spring-projects/spring-amqp#888] opened 2019-01-24 08:57 UTC
Hi guys,

I upgraded from spring-rabbit 2.1.2.RELEASE to 2.1.3.RELEASE and this resulted in an unexpected "Property 'connectionFactory' is required".

I checked the differences between the RabbitTransactionManager in 2.1.2 and 2.1.3 and found the problem. In 2.1.2 it looked like this:

```
public RabbitTransactionManager(ConnectionFactory connectionFactory) {
	this();
	this.connectionFactory = connectionFactory;
	afterPropertiesSet();
}

@Override
public void afterPropertiesSet() {
	if (getConnectionFactory() == null) {
		throw new IllegalArgumentException("Property 'connectionFactory' is required");
	}
}
```

In 2.1.3 it looks like this:

```
public RabbitTransactionManager(ConnectionFactory connectionFactory) {
	Assert.notNull(connectionFactory, "'connectionFactory' cannot be null");
	this.connectionFactory = connectionFactory;
}

@Override
public void afterPropertiesSet() {
	Assert.state(getConnectionFactory() == null, "Property 'connectionFactory' is required");
}
```

The expression in Assert.state() currently is getConnectionFactory() == null which is false because the connectionManager is set but Assert.state() reverses the expression:

```
public static void state(boolean expression, String message) {
	if (!expression) {
	  throw new IllegalStateException(message);
	}
}
```

**Comment by panchenko** [comment] 2019-01-24 09:17
This is a duplicate of #883 and the corresponding pull request is #884

**Closed** 2019-01-24 12:16 UTC
