### ISSUE TITLE
log4j2 appender issues

### ISSUE THREAD

**Issue by fenghlkevin** [spring-projects/spring-amqp#618] opened 2017-05-19 07:42 UTC
soft version: 
spring-rabbit:1.7.1.RELEASE, 
log4j2 : 2.8.2
slf4j : 1.7.7

log4j2 config:
`<?xml version="1.0" encoding="UTF-8"?>

<configuration status="warn">

    <appenders>
        <console name="console" target="SYSTEM_OUT">
            <PatternLayout pattern="[%d{HH:mm:ss:SSS}] [%p] - %l - %m%n"/>
        </console>
        
            
            
        
        <RabbitMQ name="rabbitmq_logdata_tojson"
                  host="${sys:rabbitmq_host}"
                  port="${sys:rabbitmq_port}"
                  user="${sys:rabbitmq_user}"
                  password="${sys:rabbitmq_password}"
                  virtualHost="/"
                  exchange="${sys:rabbitmq_exchange}"
                  exchangeType="${sys:rabbitmq_exchangeType}"
                  declareExchange="true"
                  durable="true"
                  autoDelete="false"
                  applicationId="${sys:rabbitmq_qname_4logdata.json}"
                  routingKeyPattern="${sys:rabbitmq_qname_4logdata.json}"
                  contentType="text/plain"
                  contentEncoding="${sys:log4j2_charset}"
                  generateId="false"
                  deliveryMode="NON_PERSISTENT"
                  charset="${sys:log4j2_charset}"
                  senderPoolSize="1" maxSenderRetries="5">
        </RabbitMQ>

        
        
            
        

    </appenders>

    <loggers>

        <logger name="${sys:rabbitmq_qname_4logdata.json}" level="info">
            <appender-ref ref="rabbitmq_logdata_tojson"/>
        </logger>

        
        
            
        

        <root level="debug">
            <appender-ref ref="console"/>
            
        </root>
    </loggers>

</configuration>`

java code:
`private static final Logger writeQueueLog= LoggerFactory.getLogger(System.getProperty("rabbitmq_qname_4logdata.json"));
writeQueueLog.info(jsonObject.toString());
`

the System.properties

`rabbitmq_qname_4logdata.json=user.behavior.countmessage.queue
rabbitmq_qname_4logdata=user.behavior.logdatainfo.queue`

when i user AMQPAppender to send message to rabbitmq, always has some other logger message.

I had debug APQPAppender source code, when method "append" has been called, all of the events is need, but the Sender is running，always has some events from other logger.

then, I changed queue to String like this : `private final LinkedBlockingQueue<String> eventsStrs = new LinkedBlockingQueue<String>();`, and add data in method append(),
I see all the value is right, bug value from events have some wrong message.

i have no idea about it, can you help me?

**Comment by garyrussell** [comment] 2017-05-19 13:00
Duplicate of [SO Question](http://stackoverflow.com/questions/44064369/spring-rabbit-use-log4j2-amqpappender/44070812#44070812).

I found this code in Log4J2...

        if (LOG_EVENT_FACTORY == null) {
            LOG_EVENT_FACTORY = Constants.ENABLE_THREADLOCALS
                    ? new ReusableLogEventFactory()
                    : new DefaultLogEventFactory();
        }

If you run with `-Dlog4j2.enable.threadlocals=false` it will be thread-safe.

I will add an option to the Spring appender to send the message on the calling thread instead of handing off to another thread, which will make using the `ReusableLogEventFactory` safe.

You can also explicitly set the event factory with `Log4jLogEventFactory`.

See __System Properties__ [here](https://logging.apache.org/log4j/2.x/manual/configuration.html).

**Closed by garyrussell** 2017-05-19 13:00 UTC
