### ISSUE TITLE
rabbit properties in application.properties cannot overwrite the dafault values

### ISSUE THREAD

**Issue by quang-do-se** [spring-projects/spring-amqp#2562] opened 2023-12-04 10:51 UTC
**In what version(s) of Spring AMQP are you seeing this issue?**

`org.springframework.boot:spring-boot-starter-amqp:3.1.6`
`org.springframework.amqp:spring-rabbit:3.0.10`

**Describe the bug**

Setting values for`spring.rabbitmq.username` and `spring.rabbitmq.password` in `application.properties` does not overwrite the default values, which are configured as `guest`.

**To Reproduce**

This repository is set up to reproduce the issue: https://github.com/quang-do-se/spring-amqp-testing

**Expected behavior**

`spring.rabbitmq.username` and `spring.rabbitmq.password`  should be updated according to what is defined in the `application.properties` file.

**Sample**

Repository: https://github.com/quang-do-se/spring-amqp-testing

<img src="https://github.com/spring-projects/spring-amqp/assets/16267107/bc55eb93-da1d-4b43-9227-765e70f533ae" width=40%>

![image](https://github.com/spring-projects/spring-amqp/assets/16267107/10a22890-dd87-4a21-b53e-24265c6367ab)

**Comment by artembilan** [comment] 2023-12-04 16:54
Thank you for the sample.
Just checked out it and ran:
```
Here are the highlights of this release:
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.6)

2023-12-04T11:51:41.739-05:00  INFO 18604 --- [           main] org.example.Main                         : Starting Main using Java 17.0.5 with PID 18604 (C:\SpringIO\tmp\spring-amqp-testing\build\classes\java\main started by abilan in C:\SpringIO\tmp\spring-amqp-testing)
2023-12-04T11:51:41.741-05:00  INFO 18604 --- [           main] org.example.Main                         : No active profile set, falling back to 1 default profile: "default"
2023-12-04T11:51:42.325-05:00  INFO 18604 --- [           main] org.example.Main                         : Started Main in 0.82 seconds (process running for 1.117)
Host: test-host
Username: test-user
Password: test-password
```

So, I cannot reproduce what you are claiming.

More over it sounds more like nothing to do with Spring AMQP, but rather Spring Boot by itself.
This project does not manage those properties.

I'm closing as `Invalid`.
If you still have some concerns about that behavior, please, consider to re-open issue in Spring Boot by itself.
Even if there is any problem, we just cannot do anything here since the code is out there in Spring Boot.

Thanks

**Closed by artembilan** 2023-12-04 16:54 UTC
Labels: type: bug, status: waiting-for-triage
