### ISSUE TITLE
Requeued async message are detected as unroutable.

### ISSUE THREAD

**Issue by Jojoooo1** [spring-projects/spring-amqp#1458] opened 2022-05-16 14:41 UTC
**In what version(s) of Spring AMQP are you seeing this issue?**

2.4.4

**Describe the bug**

When re-queuing from a Mono @RabbitListener rabbitMQ detecte the requeued message as a unroutable message.

![Screenshot from 2022-05-16 13-10-20](https://user-images.githubusercontent.com/17641873/168636963-28e9a08b-f15b-4afc-9ca0-605a38efef3b.png)
![Screenshot from 2022-05-16 13-10-28](https://user-images.githubusercontent.com/17641873/168636970-3142d097-e83d-4360-8236-4eadbfe1b3c6.png)

**To Reproduce**

```
package com.intelipoint.service.webhook.listeners;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.amqp.AmqpException;
import org.springframework.amqp.core.AmqpTemplate;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

@Slf4j
@Component
@RequiredArgsConstructor
public class WebhookListenerService {

  private final AmqpTemplate amqpTemplate;

  public static final String RETRY_HEADER = "x-retry-count";
  public static final String DELAY_HEADER = "x-delay";

  @Value("${your-exchange}")
  final String exchange;

  @Value("${your-routingkey}")
  final String routingKey;

  @RabbitListener(
      queues = "${your-queue}",
      messageConverter = "jsonConverter")
  public Mono<Void> process(final Message<LinkedHashMap<String, Object>> message) {
    try {

      final HashMap<String, String> headers = WebhookListenerService.getHeaders(message);
      final LinkedHashMap<String, Object> payload = message.getPayload();
      final Integer retryCount = WebhookListenerService.getRetryCount(headers);

      return Mono.fromRunnable(
          () -> {
            try {

              if (retryCount > 5) {
                return;
              }

              final Integer newRetryCount = retryCount + 1;
              final Integer newDelay = 10_000 * newRetryCount;

              headers.put(RETRY_HEADER, Integer.toString(newRetryCount));
              headers.put(DELAY_HEADER, newDelay.toString());

              log.info(
                  "QUEUE[webhook] requeuing with retryCount[{}] and delay[{}ms]",
                  newRetryCount,
                  newDelay);

              this.amqpTemplate.convertAndSend(
                  this.exchange,
                  this.routingKey,
                  payload,
                  m -> {
                    headers.forEach(
                        (header, value) -> m.getMessageProperties().setHeader(header, value));
                    return m;
                  });
            } catch (final AmqpException ex) {
              log.warn("QUEUE_ERROR[webhook] headers[{}] payload[{}]", headers, payload);
            }
          });
    } catch (final Exception ex) {
      return Mono.empty();
    }
  }

  public static HashMap<String, String> getHeaders(
      final Message<LinkedHashMap<String, Object>> message) {
    final HashMap<String, String> headers = new HashMap<>();
    for (final Map.Entry<String, Object> entry : message.getHeaders().entrySet()) {
      if (entry.getValue() instanceof String) {
        headers.put(entry.getKey(), entry.getValue().toString());
      }
    }

    return headers;
  }

  public static Integer getRetryCount(final Map<String, String> headers) {
    return StringUtils.isBlank(headers.get(RETRY_HEADER))
        ? 0
        : Integer.parseInt(headers.get(RETRY_HEADER));
  }
}
```

**Expected behavior**

Those re-queued message should not be detected as unroutable. It make it very difficult to create reliable alert.

**Comment by Jojoooo1** [comment] 2022-05-16 16:12
thanks @garyrussell just updated the issue.

**Comment by garyrussell** [comment] 2022-05-16 16:54
It is still not clear what the problem is what do you mean by unroutable; I assume you mean a successful reply after a failed request.

request -> requeue -> request -> reply

You need to set up the `MessageProperties.replyTo` property (which is mapped to an input header in the message). With recent versions, you can add the raw `MessageProperties` as a parameter to the listener.

In any case, most likely, the client will have timed out by the time you have retried, unless it has a long timeout; so the reply will be discarded over there.

**Comment by Jojoooo1** [comment] 2022-05-16 17:36
@garyrussell the use case is a webhook service.

- Receive message with a header named "url"
- Try sending the request through webclient
- if fails republish in same queue with delay else return;

It is working pretty well, its just that i had to silence the unroutable alert because everytime it fails the message is detected as unroutable after being published with delay.

**Comment by garyrussell** [comment] 2022-05-16 17:48
Sorry, I still don't get it; I don't see why the subsequent sends can be unroutable, unless you exhange and routing key are wrong; but then I don't get the "It is working pretty well" part.

Perhaps you can provide a minimal, complete example app so I can play with it to see what you mean.

**Comment by Jojoooo1** [comment] 2022-05-16 18:14
@garyrussell just created a repo at https://github.com/Jojoooo1/webhook-reactive-amqp
to start the project `make start`

then try publishing a message like:
![Screenshot from 2022-05-16 15-06-08](https://user-images.githubusercontent.com/17641873/168656461-336f636b-036e-4b00-94d2-ca55e5653262.png)

Config the webhook.site to return a 500 and observe the unroutable value in chart.

![Screenshot from 2022-05-16 15-06-58](https://user-images.githubusercontent.com/17641873/168656578-7f5f98e3-af10-4629-90db-b5a46c7dc39d.png)

**Comment by garyrussell** [comment] 2022-05-16 19:18
I would hardly call that "minimal"; there are too many moving parts; I meant a simple boot app that reproduces the issue; this one works fine (but see the note below):

```java
@SpringBootApplication
public class Rgh1458Application {

	public static void main(String[] args) {
		SpringApplication.run(Rgh1458Application.class, args).close();
	}

	@Autowired
	RabbitTemplate template;

	@RabbitListener(queues = "rgh1458")
	public Mono<Void> listen(Message<String> in) throws Exception {
		Integer retries = in.getHeaders().get("retries", Integer.class);
		if (retries == null) {
			retries = 0;
		}
		System.out.println(in.getPayload() + "; retries=" + retries);
		if (retries < 10) {
			int finalRetries = retries + 1;
			this.template.convertAndSend("", "rgh1458", in.getPayload(), msg -> {
				msg.getMessageProperties().setHeader("retries", finalRetries);
				return msg;
			});
		}
		return Mono.empty();
	}

	@Bean
	Queue queue() {
		return new Queue("rgh1458");
	}

	@Bean
	ApplicationRunner runner() {
		return args -> {
			this.template.convertAndSend("rgh1458", "foo");
			Thread.sleep(5_000);
		};
	}

}
```

However, on a couple of runs, I did see a spike for unroutable (drop) (and the retries were all received), so I suspect it's an accounting problem in the broker.

What's weird is the unroutable spike is between runs of my app (when the app wasn't running, my app only runs for 5 seconds, with no delays between messages).
<img width="1435" alt="Screen Shot 2022-05-16 at 3 04 14 PM" src="https://user-images.githubusercontent.com/483832/168664880-b6f5a8b4-1eb5-42fe-8be6-7fd6c372b8ee.png">

Also, the yellow spike just appears after the fact on the existing graph - see these examples:
<img width="449" alt="Screen Shot 2022-05-16 at 3 14 08 PM" src="https://user-images.githubusercontent.com/483832/168665730-96a81a8c-0645-446e-972f-c48fe8f93797.png">
<img width="442" alt="Screen Shot 2022-05-16 at 3 14 29 PM" src="https://user-images.githubusercontent.com/483832/168665761-c94b7a09-62d8-4c1e-9b89-0de608a6e393.png">

See 15:13:40



I suggest you raise the issue on the rabbitmq-users Google group.

**Comment by garyrussell** [comment] 2022-05-16 21:16
I reached out to the RabbitMQ team and they (correctly) pointed out tat my yellow spikes are publishes. Yours do look like drops.

Here is their comment on my original question to them:

>It can be a side-effect of dead-lettering due to TTL or any other reason. Messages are routed to an exchange that has no bindings => they are dropped but you won't observe it via any other metric

Closing this because I don't believe it's a Spring issue; feel free to re-open if you are able to prove otherwise.

**Closed by garyrussell** 2022-05-16 21:16 UTC
Labels: status: waiting-for-reporter, type: bug

**Comment by Jojoooo1** [comment] 2022-05-17 16:56
@garyrussell for info, when i removed the delayed message type the unroutable message disappeared.

**Comment by garyrussell** [comment] 2022-05-17 17:18
Perhaps it's an artifact of the delayed exchange plugin? I suggest you explore it with the RabbitMQ folks.
